name: fin_calc
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  adaptive_theme: ^3.6.0
  flutter_screenutil: ^5.9.3
  easy_localization: ^3.0.7
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  logger: ^2.5.0
  injectable: ^2.5.0
  get_it: ^8.0.3
  dartz: ^0.10.1
  go_router: ^14.6.2
  flutter_smart_dialog: ^4.9.8+5
  json_annotation: ^4.9.0
  moon_design: ^1.1.0
  system_design_flutter:
    path: packages/system_design_flutter
  characters: ^1.4.0
  share_plus: ^11.0.0
  bloc_concurrency: ^0.3.0
  color_shade: ^1.0.1
  material_symbols_icons: ^4.2815.1

  bloc: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  injectable_generator: ^2.6.2
  build_runner: ^2.4.13
  husky: ^0.1.7
  lint_staged: ^0.5.1
  json_serializable: ^6.9.0
  flutter_launcher_icons: "^0.14.3"
  flutter_native_splash: ^2.4.6
  rename_app: ^1.6.3

lint_staged:
  "lib/**.dart": dart format && dart fix --apply

flutter:
  uses-material-design: true
  assets:
    - lib/src/core/translations/
    - assets/images/
    - assets/icons/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#111419"
  image: assets/images/app_logo_light.png
  image_dark: assets/images/app_logo_dark.png
  android_12:
    icon_background_color: "#ffffff"
    icon_background_color_dark: "#111419"
    image: assets/images/app_logo_light.png
    image_dark: assets/images/app_logo_dark.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_launcher_icon.png"
  min_sdk_android: 21
